name: PR
permissions:
  contents: read

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm install
      - run: npm run format
      - run: npm run lint
      - run: npm run build
      - run: npm run test
